Repository eslint/config-inspector, pull requests merged in 2024-05, with the labels that each got.

#50 fix: dev time endless ERROR [unhandledRejection] read ECONNRESET
  package.json
  pnpm-lock.yaml
Labels: bug

#54 docs: update readme to use latest version
  README.md
Labels: documentation

#56 ci: reduce list of releasable tags to `feat`, `fix` and `perf`
  .github/workflows/release-please.yml
Labels: build
