Repository eslint/config-inspector, pull requests merged in 2024-04, with the labels that each got.

#17 feat: support `build` command for static hosting
  .gitignore
  bin.mjs
  components/NavBar.vue
  composables/payload.ts
  composables/types.ts
  package.json
  pnpm-lock.yaml
  server/api/get.ts
  server/api/payload.json.ts
  server/api/utils.ts
  server/tsconfig.json
  tsconfig.json
Labels: feature

#16 feat: align better with ESLint's design system
  app.vue
  components/NavBar.vue
  components/RuleItem.vue
  pages/configs.vue
  pages/rules.vue
  styles/global.css
  uno.config.ts
Labels: feature

#20 feat: use custom server host, reduce deps
  app/app.vue
  app/components/ColorizedConfigName.ts
  app/components/ColorizedRuleName.vue
  app/components/ConfigItem.vue
  app/components/GlobItem.vue
  app/components/NavBar.vue
  app/components/OptionSelectGroup.vue
  app/components/RuleItem.vue
  app/components/RuleLevelIcon.vue
  app/components/RuleList.vue
  app/components/RuleStateItem.vue
  app/components/SummarizeItem.vue
  app/composables/color.ts
  app/composables/dark.ts
  app/composables/payload.ts
  app/composables/rules.ts
  app/composables/state.ts
  app/composables/strings.ts
  app/pages/configs.vue
  app/pages/index.vue
  app/pages/rules.vue
  app/plugins/floating-vue.ts
  app/public/favicon.svg
  app/server/api/payload.json.ts
  app/server/tsconfig.json
  app/styles/global.css
  bin.mjs
  build.config.ts
  eslint.config.js
  nuxt.config.ts
  package.json
  patches/nitropack@2.9.4.patch
  pnpm-lock.yaml
  src/cli.ts
  src/configs.ts
  src/dirs.ts
  src/server.ts
  src/ws.ts
  types.ts
  uno.config.ts
Labels: feature

#23 chore: cleanup moot contents
  app/components/NavBar.vue
  app/components/RuleItem.vue
  app/pages/configs.vue
  app/pages/rules.vue
Labels: chore

#26 feat: improve how configures are resolved
  app/server/api/payload.json.ts
  package.json
  pnpm-lock.yaml
  src/cli.ts
  src/configs.ts
  src/server.ts
  src/ws.ts
  types.ts
Labels: feature

#29 fix: hide detail marker on safari
  app/styles/global.css
Labels: bug

#30 refactor: use `h3` to create server
  package.json
  pnpm-lock.yaml
  src/server.ts
Labels: chore

#32 docs: Fix typos on CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#39 fix: start watcher with `basePath`
  src/configs.ts
  src/ws.ts
Labels: bug, feature
